# Segunda Lei da Termodinâmica {#seglei}

Principalmente em países tropicais como o Brasil, refrigeradores são eletrodomésticos essenciais, e é uma tragédia  social que algumas famílias não tenham acesso à eletricidade ou aos recursos para adquirir uma "geladeira", como é comumente chamada. Para aqueles lares que possuem um refrigerador doméstico, o seu uso impede ou pelo menos retarda a degradação de alimentos e bebidas que, se submetidas às altas temperaturas ambientes, sofreriam muito rapidamente a ação bacteriana e fúngica que impede o seu consumo.

Um refrigerador precisa manter no seu interior um ambiente frio, com temperaturas menores que a do ambiente, suficiente baixas para impedir a ação danosa descrita no parágrafo anterior. Um meio simples de criar essa separação é simplesmente armazenar alimentos e bebidas em uma caixa com gelo, onde as paredes sejam de material isolante. Eram assim as primeiras geladeiras, como o próprio nome indica: armários de gelo, onde um grande bloco de gelo (que poderia ser minerado de lagos ou rios congelados) é colocado em uma prateleira superior, e os alimentos são armazenados embaixo; por convecção natural, o ar esfria em contato com o gelo, absorve calor dos alimentos, e sobe, cedendo energia para o gelo, que então derrete - o que é o principal problema. Esse tipo de dispositivo tem uma vida útil definida; quando o bloco de gelo derrete, a água precisa ser drenada e o bloco reposto, antes que a temperatura do gabinete refrigerado volte a subir.

O desafio de engenharia é criar um sistema que funcione em ciclos, continuamente, e com um sistema fechado, sem precisar repor ou drenar fluidos. Será que é possível encontrar algum material ou sistema que refrigere continuamente um ambiente isolado? A resposta, baseada em experimentos, é não:  *nunca* se observou nenhum tipo de material ou arranjo que permitisse um ambiente frio transferir calor para o ambiente quente, funcionando em ciclos em um sistema fechado,  sem nenhum outro tipo de ação externa, ou uma "ajuda" para isso acontecer - esse fato é conhecido como o **Enunciado de Clausius da Segunda Lei da Termodinâmica**.

Um refrigerador não viola o enunciado de Clausius porque nesse caso *há* um elemento externo - um compressor, que consome trabalho elétrico e transfere trabalho para o fluido refrigerante que circula pelo sistema (fechado, sem sair ou entrar do sistema como um todo) e realiza as trocas de calor - do ambiente frio para o fluido e depois do fluido para o ambiente quente. 

A potência do compressor é algo que pagamos - literalmente. É de interesse de engenharia, portanto, encontrar maneiras de minimizar essa potência. Ela não pode ser zero pelo Enunciado de Clausius. Mas o quão pequena ela pode ser?

Talvez surpreendentemente, essa pergunta está ligada a um conceito que parece não relacionado com o de refrigeradores - o de máquinas térmicas. Uma máquina térmica é um dispositivo cíclico que recebe calor de uma fonte (também chamado de reservatório) quente, converte uma parte em  trabalho, e descarta o calor residual em uma fonte fria. Uma usina termelétrica é talvez o exemplo mais simples: a combustão de um combustível com ar gera uma frente de chama quente, que transfere calor (principalmente por radiação) para uma tubulação onde a água líquida é vaporizada e superaquecida; este vapor movimenta uma turbina e perde pressão, e esse vapor a baixa pressão é condensado de volta (e o calor é transferido, geralmente, para uma grande torre de arrefecimento). Neste caso, nós *ganhamos* a potência gerada, e vem a pergunta: qual o limite máximo da potência gerada? É possível uma eficiência térmica (razão entre potência gerada e calor fornecido) de 100%?

Assim como no caso de refrigeradores, baseamo-nos em observações experimentais para afirmar que não: é impossível construir uma máquina térmica que funcione em ciclos com um sistema fechado, *gere* potência para fora do sistema e troque calor com apenas um reservatório térmico. Esse fato é conhecido como o **Enunciado de Kelvin-Planck da Segunda Lei da Termodinâmica**.

A Segunda Lei não é uma equação, mas uma desigualdade: ela impõe limites sobre a eficiência de máquinas térmicas e refrigeradores. Em termos pedagógicos, isso parece fazer a Segunda Lei não ser tão priorizada quanto a Primeira Lei (ver Cap. \@ref(#primlei)), com suas equações relacionando energia, calor e trabalho que podem ser *resolvidas* para alguma grandeza de interesse [@bib:bejan].

Os trabalhos de Carnot respondem às perguntas colocadas neste texto: a chave para maximizar a eficiência é garantir processos e ciclos *reversíveis*, isto é, que possam ser executados em qualquer sentido sem diferenças para o sistema e a vizinhança. Em termos práticos, isto requereria trocadores de calor com área infinita, de maneira que a fonte e o fluido de trabalho estejam sempre em equilíbrio térmico.

A menor potência consumida pelos refrigeradores é a potência de um refrigerador reversível. Para provar isso, vamos imaginar dois refrigeradores, R (de reversível) e G (de geral, que pode ser reversível ou não), entre dois reservatórios, a $T_{\mathrm{H}}$ e $T_{\mathrm{L}}$. Vamos imaginar que os dois recebam a mesma *capacidade de refrigeração* da fonte fria, ${Q}_{\mathrm{L}}$ (sendo este o calor transferido por ciclo completado). Vamos então supor que o refrigerador G é mais eficiente ou pelo menos tão eficiente quando o refrigerador real, $W_{\mathrm{G}} \le W_{\mathrm{R}}$ (onde $W$ é o trabalho consumido pelo sistema). Pela Primeira Lei , o calor rejeitado para a fonte quente por cada sistema ao final de um ciclo é:

$${Q}_{\mathrm{H}} = {Q}_{\mathrm{L}} + W$$

Onde todas as grandezas são admitidas como positivas. Logo, $Q_{\mathrm{H,G}} < Q_{\mathrm{H,R}}$

Como o sistema R é reversível, podemos transformá-lo em uma máquina térmica, onde todos os valores de transferências de energia são preservados, e o sentido é invertido. Mas agora o que acontece: o refrigerador R recebe uma grande quantidade de calor da fonte quente, gera trabalho, e transfere calor que, sendo na mesma temperatura e de mesma magnitude, pode ser direcionado diretamente para o refrigerador G. Este vai consumir uma parte do trabalho gerado (já ele consome menos que o refrigerador reversível gera), rejeitar uma pequena quantidade de calor (idem). O sistema combinado é um sistema que troca calor com apenas um reservatório (já que o reservatório frio é inútil e, como falado, podemos desviar de uma máquina para outra) e gera uma quantidade líquida de trabalho. Isto viola o Enunciado de Kelvin-Planck - logo, entre duas temperaturas, não conseguimos fazer um refrigerador mais eficiente que um reversível. Se G também for reversível, podemos repetir o exercício e perceber que G não pode ser mais eficiente que R, e R não pode ser mais eficiente que G, e portanto ambos são equivalentes. 

Uma das métricas de desempenho de refrigeradores é o *coeficiente de performance*:

$$\mathrm{COP} = \frac{{Q}_{\mathrm{L}}}{W}$$

E, pelo que foi falado todos os refrigeradores reversíveis entre os mesmos reservatórios (caracterizados pelas mesmas temperaturas) possuem o mesmo COP.

Mas qual é esse valor? Observe que, pela Primeira Lei:

$$\mathrm{COP} = \frac{{Q}_{\mathrm{L}}}{{Q}_{\mathrm{H}} - {Q}_{\mathrm{L}}}$$

A forma matemática da segunda lei é a Desigualdade de Clausius:

$$\oint \frac{\delta Q}{T} \le 0$$

Ou seja, ao longo de um ciclo, se somarmos a razão entre o calor transferido dividido pela temperatura na fronteira em que esse calor transferido, temos uma grandeza não-positiva. Se essa integral for positiva, é possível provar que os Enunciados acima são violados.

A igualdade na desigualdade de Clausius corresponde ao caso limite, que como vimos, é o da reversibilidade. Assim, colocamos um volume de controle ao redor do condensador de tal maneira que a sua fronteira esteja na temperatura quente, e em volta do evaporador onde a fronteira esteja na temperatura fria. No caso reversível, então:

$$\frac{{Q}_{\mathrm{L}}}{T_{\mathrm{L}}} = \frac{{Q}_{\mathrm{H}}}{T_{\mathrm{H}}}$$

E portanto, dividindo a equação do COP por $T_{\mathrm{L}}$:


$$\mathrm{COP}_{\mathrm{rev}} = \frac{{T}_{\mathrm{L}}}{{T}_{\mathrm{H}} - {T}_{\mathrm{L}}}$$

Por que o COP de refrigeradores é menor que o de reversíveis (ou seja, por que eles precisam de mais potência para mesma capacidade de refrigeração)? Por causa de desvios da reversibilidade. Se um condensador é mal dimensionado, o fluido vai escoar muito mais quente o ar em volta; esse processo não pode ser revertido pois, se este refrigerador funcionar como máquina térmica, o trocador não vai conseguir absorver calor da fonte quente (ar ambiente) estando mais quente que ele!

## Geração de entropia e irreversibilidades

Muito da pesquisa e desenvolvimento em engenharia é identificar maneiras de trazer o COP de refrigeradores reais mais próximo do COP de Carnot, através da identificação das perdas. Identificar (e priorizar) irreversibilidades, equilibrando desempenho termodinâmico com outros fatores (como custo, peso, ruído), é o desafio cotidiano do engenheiro de ciências térmicas. 

Em minha experiência com refrigeração magnética, uma tecnologia inovadora baseada em materiais sólidos, os trabalhos que tiveram mais impacto (discussões em congressos e citações em revistas) são aqueles que investigam em detalhes os processos que mais estão contribuindo para essa perda de eficiência.

A desigualdade de Clausius pode ser transformada em uma equação:

$$S_{\mathrm{ger}} = -\oint \frac{\delta Q}{T} \ge 0$$

A *geração de entropia* é uma medida do qual desigual é a desigualdade de Clausius. Processos e ciclos totalmente reversíveis não geram entropia.

O aumento da potência gerada por usinas de vapor e gás e motores de combustão interna é uma história de minimização de geração de entropia [@bib:bejan]; a crise de energia e de petróleo da década de 1970 mostrou que a energia é escassa e que tem *qualidade*, devendo ser aproveitada da melhor forma possível, sem perdas [@bib:Souza1980].

Portanto, nenhuma análise de engenharia está completa sem uma *Análise de Segunda Lei*: determinar quais processos geram mais entropia, i.e., onde a variação da *propriedade termodinâmica* chamada entropia não pode ser explicada apenas pela transferência de calor, e estes são os processos por onde a otimização deve começar.

Na Análise de Segunda Lei de motores de combustão interna, por exemplo, um resultado comum é o processo de exaustão concentra a maior parte da geração de entropia: os gases se expandem no tempo motor, mas por restrições de volume do motor eles não conseguem se expandir até a pressão atmosférica. Logo, gases pressurizados são simplesmente descarregados.

Duas soluções são comuns:

1. Colocar uma turbina no sistema de escape, de maneira a aproveitar essa pressão (motores turboalimentados)
2. Restringir a quantidade de fluido que entra, de maneira a conseguir abaixar mais a pressão na expansão e *aproveitá-la* melhor.

